<?php

return [
    '/' => 'Main:index',
    '/main' => 'Main:index',
    '/main/index' => 'Main:index',
    '/gallery' => 'Gallery:index',
    '/gallery/index' => 'Gallery:index',
    '/gallery/show' => 'Gallery:show',
    '/gallery/create' => 'Gallery:create',
    '/gallery/update' => 'Gallery:update',
    '/gallery/delete' => 'Gallery:delete',
    '/user' => 'User:index',
    '/user/index' => 'User:index',
    '/user/contacts' => 'User:contacts',
    '/post' => 'Post:index',
    '/post/index' => 'Post:index',
    '/post/read' => 'Post:read',
    '/post/create' => 'Post:create',
    '/post/update' => 'Post:update',
    '/post/delete' => 'Post:delete',
    '/user/create' => 'User:create',
    '/user/update' => 'User:update',
    '/user/delete' => 'User:delete',
];
